# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build crm/services/users/cmd/users

    - name: Run gRPC server in background
      run: |
        go run crm/services/users/cmd/users/main.go --config=./config/local_git.yaml &
        sleep 2 

    - name: Test
      run: go test crm/services/users/tests
