# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o users crm/services/users/cmd/users

    - name: Run gRPC server in background
      run: |
        ./users &
        sleep 2
      env:
        Env: ${{ vars.ENV }}
        DbURL: ${{ vars.DB_URL }}
        GrpcPort: ${{ vars.GRPC_PORT }}
        GRPC_TIMEOUT: ${{ vars.GRPC_TIMEOUT }}
        LOGGER_SERVICE: ${{ vars.LOGGER_SERVICE }}
        LOGGER_LOG_LEVEL: ${{ vars.LOGGER_LOG_LEVEL }}
        LOGGER_LOG_FILE: ${{ vars.LOGGER_LOG_FILE }}

    - name: Test
      run: go test crm/services/users/tests
